[build-system]
requires = ["maturin>=1.14,<2.0"]
build-backend = "maturin"

[project]
name = "solars"
requires-python = ">=3.11,<=3.14"
readme = "README.md"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "numpy>=1.26",
]

[tool.maturin]
data = "solars.data"

[project.optional-dependencies]
comparison = ["pandas>=2.0", "pvlib>=0.11"]
